version: '3.7'
#https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html#docker-cli-run-prod-mode
#first run this command below 
#wsl -d docker-desktop
#sysctl -w vm.max_map_count=262144
services:
  elasticsearch:
    image: "elasticsearch:7.9.3" 
    container_name: elasticsearch
    restart: unless-stopped    
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      bootstrap.memory_lock: "true"
      discovery.seed_hosts: elasticsearch
      ES_JAVA_OPTS: -Xms256m -Xmx256m 
    volumes:
      - "es-data-es01:/usr/share/elasticsearch/data"
    ulimits:
      memlock:
        soft: -1
        hard: -1 
volumes:
  es-data-es01:
